package com.clotus.entity;

import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.speech.tts.TextToSpeech;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity {
 private ClotusCore core; private LinearLayout root, content; private TextView title, transcript; private EditText input; private TextToSpeech tts;
 private int teal=Color.rgb(101,230,211), bg=Color.rgb(7,10,18), panel=Color.rgb(16,23,36);
 @Override public void onCreate(Bundle b){super.onCreate(b); try{core=new ClotusCore(this); build();}catch(Exception e){fatal(e);} }
 private TextView tv(String s,int size){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(size);v.setPadding(18,12,18,12);return v;}
 private void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg); title=tv("CLOTUS  /  ENTITY RUNTIME",20);title.setTextColor(teal);root.addView(title); ScrollView scroll=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1)); LinearLayout nav=new LinearLayout(this); String[] pages={"CONVERSE","STATE","MEMORY","AUDIT"}; for(String p:pages){Button x=new Button(this);x.setText(p);x.setTextColor(teal);x.setOnClickListener(v->show(p));nav.addView(x,new LinearLayout.LayoutParams(0,60,1));}root.addView(nav);setContentView(root);show("CONVERSE");}
 private void show(String page){content.removeAllViews(); if(page.equals("CONVERSE")){content.addView(tv("LOCAL CORE  •  PERSISTENT  •  AUDITABLE",13));transcript=tv("CLOTUS: Sistema iniciado. Identidad cargada.",17);transcript.setBackgroundColor(panel);content.addView(transcript);input=new EditText(this);input.setHint("Escribe a CLOTUS…");input.setTextColor(Color.WHITE);input.setHintTextColor(Color.GRAY);content.addView(input);Button send=new Button(this);send.setText("SEND / REMEMBER");send.setOnClickListener(v->{try{String r=core.respond(input.getText().toString());transcript.setText("CLOTUS: "+r);if(tts!=null)tts.speak(r,TextToSpeech.QUEUE_FLUSH,null,"clotus");input.setText("");}catch(Exception e){transcript.setText("CORE ERROR: "+e.getMessage());}});content.addView(send);Button snap=new Button(this);snap.setText("CREATE SNAPSHOT");snap.setOnClickListener(v->{try{transcript.setText("SNAPSHOT: "+core.createSnapshot("user-request"));}catch(Exception e){transcript.setText(e.toString());}});content.addView(snap);} else if(page.equals("STATE")){content.addView(tv("IDENTITY",18));content.addView(tv(core.identity().toString(),13));content.addView(tv("CAPABILITIES",18));content.addView(tv(core.capabilities(this).toString(),13));}else if(page.equals("MEMORY")){content.addView(tv("MEMORY / "+core.memories().length()+" records",18));content.addView(tv(core.memories().toString(),13));}else{content.addView(tv("STRUCTURED AUDIT / "+core.audit().length()+" events",18));content.addView(tv(core.audit().toString(),12));}}
 private void fatal(Exception e){new AlertDialog.Builder(this).setTitle("CLOTUS CORE FAILED").setMessage(e.toString()).setPositiveButton("OK",null).show();}
 @Override protected void onPause(){super.onPause();try{if(core!=null)core.persist();}catch(Exception ignored){}}
}
